spring.application.name=datacollector
spring.datasource.url=jdbc:postgresql://localhost:5433/datacollector
spring.datasource.username=datacollector
spring.datasource.password=datacollector

spring.jpa.hibernate.ddl-auto=update
server.port=8081